name: Build Flutter AAB with Real Keystore
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos || true
    
    - name: Run tests
      run: flutter test || true
    
    # ✅ NEW: Use your REAL keystore instead of creating fake one
    - name: Decode and setup real keystore
      run: |
        echo "Setting up REAL WashMoose keystore..."
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/washmoose-release-key.jks
        echo "Keystore decoded successfully"
    
    # ✅ NEW: Create key.properties with your REAL credentials
    - name: Create key.properties with real credentials
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=washmoose-release-key.jks" >> android/key.properties
        echo "Real key.properties created"
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Build App Bundle (AAB) with REAL signing
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-real-signed
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload AAB (REAL KEYSTORE)
      uses: actions/upload-artifact@v4
      with:
        name: release-aab-real-signed
        path: build/app/outputs/bundle/release/app-release.aab
